aes: aes128.h aes128.cpp
	@g++ aes128.cpp -o main -std=c++11 && ./main

rc4: rc4.cpp
	@g++ rc4.cpp -o main -std=c++11 && ./main

sha: sha256.h sha256.cpp
	@g++ sha256.cpp -o main -std=c++11 && ./main

cr: main
	@rm main